name: Continuous Integration

env:
  KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
  KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install package and deps
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Restore cached data
      id: cache-data-restore
      uses: actions/cache/restore@v4
      with:
        path: data
        key: data

    - name: Generate data hash
      id: hash-data
      run: echo "hash=$(find data -type f -exec md5sum {} + | md5sum | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: Run tests
      run: |
        python -m unittest discover -v -s mir -p "test_*.py"

    - name: Generate new data hash
      id: hash-data-new
      run: echo "hash=$(find data -type f -exec md5sum {} + | md5sum | awk '{ print $1 }')" >> $GITHUB_OUTPUT

    - name: Save data cache
      id: cache-data-save
      if: steps.hash-data.outputs.hash != steps.hash-data-new.outputs.hash
      uses: actions/cache/save@v4
      with:
        path: data
        key: data
    
    - name: Notify same data
      if: steps.hash-data.outputs.hash == steps.hash-data-new.outputs.hash
      run: echo "Data did not change so no need to save cache"